#
# This files holds the parameters for the dynamic_model, planner, and octomap
#

fuzzy_constant_speed: 5 # m/s
max_angular_vel: 1     # rad/s
timestep: .001
debug_level: 2
planner_resolution: .01
state_checker_resolution: .01   # 1%
propagation_step_size: .1
visualize_planner: 1
goal_bias: .1
goal_bias2: .5
distance_weights: [1,1,0,0]
add_intermediate_states: true
num_control_samples: 2
seed: 9 #useful for debugging and getting deterministic results
heading_heuristic: 0  # 0 -> 1, 1 is try to match heading, 0 is try to match position
forward_variance: 1
angular_variance: .3
p_gain: 1
goal_tolerance: .01 #goal region is a square +-goal_tolerance
max_gp_runtime: 600 #maximum global planner runtime in seconds
