TerrainMap:
    filter_radius: .5
    elevation_map_res: .1
    normal_radius: .5
    smoothness_threshold: .03
    curvature_threshold: .5
    num_neighbors: 30
    num_neighbors_avg: 5
    plot_res: 4
    occupancy_threshold: .05
LocalMap:
    occupancy_threshold: .05
    smoothness_threshold: .03
    curvature_threshold: .5